### ISSUE TITLE
👷‍♂️ whitelists won't work when msg.sender of the withdraw is not `from`

### ISSUE THREAD

**Issue by zkSoju** [cypherprotocol/cypher-contracts#22]
https://github.com/cypherprotocol/cypher-contracts/blob/aa9068e5454769e07a7a31f5dc5b58b8706ee918/src/CypherEscrow.sol#L78

https://github.com/cypherprotocol/cypher-contracts/blob/aa9068e5454769e07a7a31f5dc5b58b8706ee918/src/CypherEscrow.sol#L91

Our current implementation of escrowTokens takes in `from` and `to` which causes this test to fail because the user being whitelisted is not `from`. `from` in this case (and usually) is the protocol that the user is trying to withdraw from.

https://github.com/cypherprotocol/cypher-contracts/blob/aa9068e5454769e07a7a31f5dc5b58b8706ee918/test/CypherVaultETH.t.sol#L150-L152

**Comment by bmwoolf** [comment]
we can use `delegateCall()` from the `cypher` code they paste in the protocol, which will forward the msg.sender. 

or (i recommend) in the `cypher` code, we can pass along another variable of the original caller from the protocol code. the latter option will introduce fewer attack vectors than using `delegateCall()`
